version: '3.8'
networks:
  app_network:
    driver: bridge

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules 
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - app_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.${ENV:-production}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network